<div id="recordListTable" class="dataTablesDefault">
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
		<thead>
		<tr>
			<th>ID</th>
			<th>Value</th>
		</tr>
		</thead>
	<?php foreach($this->getRecords() as $idx => $rec): ?>
		<tr>
			<td id="row_<?php echo $idx; ?>" style="cursor: pointer;">
				<?php echo $rec['id']; ?>
			</td>
			<td><?php echo $rec['val']; ?></td>
		</tr>	
	<?php endforeach; ?>
	</table>
</div>