<div id="recordListTable" class="dataTablesDefault">
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="myTable" width="100%">
		<thead>
		<tr>
			<th></th>
			<th>ID</th>
			<th>Value</th>
		</tr>
		</thead>
	<?php foreach($this->getRecords() as $rec): ?>
		<tr id="row_<?php echo $rec['rowNum']; ?>">
			<td>
				<span class="deleteRow" style="cursor:pointer;font-weight:bold; color:red;">X</span>
			</td>
			<td>
				<span class="editRow" style="cursor:pointer;"><?php echo $rec['id']; ?></span>
			</td>
			<td><?php echo $rec['val']; ?></td>
		</tr>	
	<?php endforeach; ?>
	</table>
</div>