<script src="scripts/indexController.js"></script>
<div style="width: 600px;">
	<?php require_once('./view/partial/recordListTableAction.phtml'); ?>
</div>
<br clear="all" />
<div>
	ID: <span id="inputid"></span><br />
	Value: <input id="inputval" class="updateStore" type="text" name="inputval" /><br />
	<input id="inputSave" value="Add" type="button" /> <input id="inputCancel" value="Cancel" type="button" />
</div>
