<script src="scripts/indexController.js"></script>
<div style="width: 600px;">
	<?php require_once('./view/partial/recordListTableAction.phtml'); ?>
</div>
<br clear="all" />
<input type="button" value="Add" id="inputAdd" />
<div id="inputEdit">
	ID: <span id="inputId"></span><br />
	Value: <input id="inputVal" class="updateStore" type="text" name="inputVal" />
<input id="inputSave" value="Save" type="button" />
</div>
